### ISSUE TITLE
Установка на Mac OS

### ISSUE THREAD

**Issue by nikitastupin** [partizand/finquote#1]
1. Скопировать файл `~/Downloads/finquote/lib/Finance/Quote/Moex.pm` в `/Library/Perl/5.18/Finance/Quote/Moex.pm`
2. Дописать в файл `/Library/Perl/5.18/Finance/Quote.pm` использование модуля `Moex` (`@modules = qw/AEX ... Moex/;`, аналогично https://github.com/partizand/finquote/blob/master/pic/quote-add.gif)
3. В Gnucash выбрать акцию, которую хотите обновлять и ставите галочку напротив `Get Online Quotes`, выбираем `Unknown`, в выпадающем меню выбираем `micex`

**Comment by partizand** [comment]
добавил путь /Library/Perl/5.18/Finance/Quote в инструкцию. Остальное аналогично другим ОС.
Спасибо.
