### ISSUE TITLE
После обновления GnuCash до 5.0  модуль перестал работать.

### ISSUE THREAD

**Issue by Mark-Seem** [partizand/finquote#11]
Обновил GnuCash до 5.0 и заодно Finance:Quote после этого модуль перестал работать. До этого все работало. Проверка выдает следующую ошибку 
![image](https://user-images.githubusercontent.com/104092086/233095588-4166e348-eb64-4667-9e37-529c67439c80.png)

Подскажите, пожалуйста, с чем это может быть связано?

**Comment by partizand** [comment]
В 5 версии поменяли работу с котировками. Не разбирался еще. Сижу на debian, а там древние версии GnuCash.
Дойдут руки посмотрю.

The Online Quotes facility has been completely rewritten and the old gnc-fq-check, gnc-fq-dump, and gnc-fq-helper programs have been replaced with finance-quote-wrapper. The functions performed by those programs may now be accomplished by passing commands to gnucash-cli -Q, see gnucash-cli --help for specifics. The perl module requirements have changed with the rewrite: The new version doesn't need Date::Manip but needs JSON::Parse instead. gnc-fq-update has been, er, updated to reflect that.

**Comment by Mark-Seem** [comment]
Спасибо, на 4.13 все продолжает работать.  На 5 версию обновляться, значит, пока рано.

**Comment by ddarwish** [comment]
Just vote up to fix this issue

**Comment by fertkir** [comment]
Добавлю контекста:
```bash
❯ gnucash-cli --quotes get ~/my.gnucash
Price retrieval failed: Failed to initialize Finance::Quote: missing_modules JSON::Parse
```
Починил: `cpan JSON::Parse`

**Comment by fertkir** [comment]
Появилась другая ошибка:
```bash
❯ gnucash-cli --quotes dump moex_stock FXRU
Price retrieval failed: Finance::Quote check returned error Subroutine methods redefined at /usr/local/share/perl5/5.36/Finance/Quote/Moex.pm line 56.
Subroutine labels redefined at /usr/local/share/perl5/5.36/Finance/Quote/Moex.pm line 82.
```
Выглядит так, что Finance::Quote какую-то проверку своих модулей добавили.

**Comment by fertkir** [comment]
Вот так заработало: https://github.com/partizand/finquote/pull/12/files
Разумеется, в таком виде вливать не предлагаю.

**Comment by partizand** [comment]
> Вот так заработало: https://github.com/partizand/finquote/pull/12/files Разумеется, в таком виде вливать не предлагаю.

Спасибо, посмотрю, проверю и добавлю
Хотя думаю в реквесте достаточно удалить закомментированное и его можно было бы принять, после проверки работы

**Comment by fertkir** [comment]
@partizand, обновил pr

**Comment by partizand** [comment]
Исправлено, просьба проверить
В cpan чуть позже выложу

**Comment by partizand** [comment]
Исправлено в релизе https://github.com/partizand/finquote/releases/tag/v0.6

**Comment by PingWIn87** [comment]
а когда ждать сборку в cpan?

**Comment by partizand** [comment]
> а когда ждать сборку в cpan?

cpan обновил
