### ISSUE TITLE
Не могу получить котировки для облигаций

### ISSUE THREAD

**Issue by PingWIn87** [partizand/finquote#2]
Из readme совсем непонятно как получить тикеты для облигаций. Например для ОФЗ 29006
https://www.moex.com/ru/issue.aspx?board=TQOB&code=SU29006RMFS2&utm_source=www.moex.com&utm_term=ru000a0jv4l2
На сайте биржи в поле Краткое наименование указано кириллицей "ОФЗ 29006". На скриншоте из readme видно, что тикет задаётся латиницей, однако поясняющий текст к скриншоту утверждает, что надо вводить кириллицу. Отсюда путаница.
Как всё-таки получить тикет для облигаций, чтобы подтягивались котировки?

**Comment by partizand** [comment]
Нужно использовать код ценной бумаги. Для ОФЗ 29006 - это SU29006RMFS2.

**Comment by PingWIn87** [comment]
Спасибо.
Для ОФЗ сработало. 
Для корпоративных облиг, увы, нет.
Для примера RU000A0JXQ85

**Comment by partizand** [comment]
Для корпоративных облигаций нужно использовать другой модуль: moex_bond

**Comment by PingWIn87** [comment]
> Для корпоративных облигаций нужно использовать другой модуль: moex_bond

я именно так и делаю.

**Comment by RollingRusty** [comment]
Я попробовал использовать moex_bond_ofz_nkd/moex_bond_ofz и наткнулся на то, что напр. для RU000A0JWQ45 и RU000A101RB4 я мог получить котировки. Для секции ВДО этот метод, увы, не работает...

Может быть это связано с изменением адресов котировок?  
moex_bond_ofz_nkd/moex_bond_of работает с "board=TQCB" где "Т+: Облигации - безадрес."
https://www.moex.com/ru/issue.aspx?board=TQCB&code=RU000A0JWQ45&utm_source=www.moex.com&utm_term=ru000a0jwq45 
но не работает с "board=TQIR" где "Т+ Облигации ПИР - безадрес."
https://www.moex.com/ru/issue.aspx?board=TQIR&code=RU000A100DC4&utm_source=www.moex.com&utm_term=ru000a100dc4

Upd.
Предыдущая ссылка на "все остальное" https://iss.moex.com/iss/engines/stock/markets/bonds/boardgroups/7/securities.csv возвращает пустую таблицу и здесь https://iss.moex.com/iss/engines/stock/markets/bonds/boardgroups/ видно, как адреса поменялись... 

Буду признателен за обновление!

**Comment by partizand** [comment]
> Спасибо.
> Для ОФЗ сработало.
> Для корпоративных облиг, увы, нет.
> Для примера RU000A0JXQ85

Насколько я посмотрел, корпоративные облигации переместились в Т+. Попробуйте получить RU000A0JXQ85 через moex_bond_ofz

**Comment by partizand** [comment]
Обновил получение облигаций, добавил функций. Посмотрите.
Возможно вы знаете как получать все облигации без разбиения на группы. Я не нашёл.
На cpan отправил запрос. Но там замороченно, я уже не понмю как правильно обновлять. Если правильно сделал, то через пару дней будет обновлено на cpan.

**Comment by RollingRusty** [comment]
Спасибо большое - все работает как по маслу у меня. Поменял moex.pm и обновил источники для облигации. Пока, к сожалению, не нашел возможность получать все облигации из одного источника...
Думаю, вопрос можно закрыть.
