### ISSUE TITLE
Wrong bond price in case of nominal less (other?) than 1000

### ISSUE THREAD

**Issue by RollingRusty** [partizand/finquote#6]
Owning two bonds RU000A0JUQB7 (https://www.moex.com/ru/issue.aspx?board=TQCB&code=RU000A0JUQB7&utm_source=www.moex.com&utm_term=ru000a0juqb7) and RU000A0ZZ0L6 (https://www.moex.com/ru/issue.aspx?board=TQCB&code=RU000A0ZZ0L6&utm_source=www.moex.com&utm_term=ru000a0zz0l6) where initial nominal value was 1000, but now is 50 roubles due to amortization. I am not sure, but it seems that finquote fetches "Первоначальная номинальная стоимость" insteand of "Номинальная стоимость". Any ideas how I can fix this?

**Comment by partizand** [comment]
Yes. I`ll fix it, lately.

**Comment by partizand** [comment]
Hi.
Fix in version 0.5.

**Comment by RollingRusty** [comment]
Thank you very much! Works like a charm 👍
