### ISSUE TITLE
Ошибка при получении котировок

### ISSUE THREAD

**Issue by PingWIn87** [partizand/finquote#7]
При попытке получить котировки Получаю окно с текстом: "Произошла неизвестная ошибка при получении котировок цен"
Бумага заведена как на скриншоте. Скриншот с ошибкой тоже будет приложен.
![image](https://user-images.githubusercontent.com/31959967/110956915-b540b700-837d-11eb-9f9c-ed3342cba821.png)

![image](https://user-images.githubusercontent.com/31959967/110956801-96dabb80-837d-11eb-8aab-cb1fa2dd3ec2.png)

**Comment by RollingRusty** [comment]
У меня показывает котировки с Вашими параметрами...
![moex-banep](https://user-images.githubusercontent.com/72160608/110958981-4acc4e80-835e-11eb-8370-abd6ea7be405.jpg)
Вот результат:
![banep-quotes](https://user-images.githubusercontent.com/72160608/110959542-da71fd00-835e-11eb-83f5-a4f8d6d11e81.jpg)

**Comment by PingWIn87** [comment]
А как бы мне понять, что я не так делаю?
Логи где можно посмотреть

**Comment by RollingRusty** [comment]
Это первая акция или другие работают? Удалить и снова завести? Я тикер вручную ввел, не скопировал...
Я, к сожалению, не программист, только пользователь...

**Comment by PingWIn87** [comment]
Я использую базу с другого компьютера, где был установлен данный модуль.
Поставил на новой машине и получаю  вот такую ошибку. При этом не могу понять, куда смотреть, чтобы понять, что идёт не так.

**Comment by partizand** [comment]
Логов нет. Возможно ошибка не в Башнефти, а где-то в другой котировке. Например валюты. Нужно отключить все остальное.
Попробуйте открыть https://iss.moex.com/iss/engines/stock/markets/shares/boardgroups/57/securities.csv, доступна ли эта ссылка?

**Comment by PingWIn87** [comment]
Добрый день.
Ссылка доступна, скачивается табличка. Отключил получение котировок для всех бумаг, кроме Башнефти. Результат тот же.
Вот список заведённых бумаг.
![image](https://user-images.githubusercontent.com/31959967/112099922-e66b8380-8bd6-11eb-85f5-41654ad7ced5.png)

**Comment by partizand** [comment]
Для проверки создайте такой файл скрипта perl (например с названием price_from_cmd.pl)
```
##!/usr/bin/perl -w

use Finance::Quote;

my $module = "Moex";

my $method = "moex_stock";

my $quoter = Finance::Quote->new($module);

my $ticker="BANEP"; # Башнефть


my %info = $quoter->fetch($method, $ticker); 
print "$ticker: \n";
print "   date: $info{$ticker,'date'}\n";
print "   price: $info{$ticker,'price'}\n";
print "   currency: $info{$ticker,'currency'} \n";
print "   isodate: $info{$ticker,'isodate'} \n";

```
Запустите его
```
perl price_from_cmd.pl
```
Должна отобразится цена

Так все работает, проблема на вашей стороне. Пробел в названии тикера, еще что-то, не могу подсказать.

**Comment by PingWIn87** [comment]
Скрипт отработал.
Проверил как заведена бумага - ничего криминального не нашёл. На старом компьютере всё работало.
Проблемы начались после переезда на новую машину.

**Comment by PingWIn87** [comment]
Обновил GnuCash до 4,5, при попытке получить котировки получил внятную ошибку, связанную с Perl. Выполнил рекомендации, которые давались к этой ошибке и всё заработало.
Тикет можно можно закрывать.
